<a href="https://colab.research.google.com/github/Antara80978/Numpy-Filtering/blob/main/task13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np

# Create a NumPy array
data = np.array([25, 45, 60, 75, 90, 35, 50, 85, 100, 40])

print("Original Array:")
print(data)

# Filter values greater than 50
above_50 = data[data > 50]
print("\nValues greater than 50:")
print(above_50)

# Filter values less than 50
below_50 = data[data < 50]
print("\nValues less than 50:")
print(below_50)

# Filter values equal to 50
equal_50 = data[data == 50]
print("\nValues equal to 50:")
print(equal_50)

# Filter values greater than or equal to 75
above_or_equal_75 = data[data >= 75]
print("\nValues greater than or equal to 75:")
print(above_or_equal_75)

# Filter values between 40 and 80
between_40_80 = data[(data >= 40) & (data <= 80)]
print("\nValues between 40 and 80:")
print(between_40_80)

# Display the Boolean condition
condition = data > 50
print("\nBoolean Array (data > 50):")
print(condition)

Original Array:
[ 25  45  60  75  90  35  50  85 100  40]

Values greater than 50:
[ 60  75  90  85 100]

Values less than 50:
[25 45 35 40]

Values equal to 50:
[50]

Values greater than or equal to 75:
[ 75  90  85 100]

Values between 40 and 80:
[45 60 75 50 40]

Boolean Array (data > 50):
[False False  True  True  True False False  True  True False]
